# Site Settings
locale: "zh-CN"
title: "郭开喆"
description: "郭开喆，东南大学青年首席教授、博士生导师，研究方向为用于 6G 高速通信和感知的射频 CMOS 集成电路设计。"
url: "https://jiaruihe80-crypto.github.io"
baseurl: "/guo-lab-demo"
repository: "jiaruihe80-crypto/guo-lab-demo"
google_scholar_stats_use_cdn: false

# Analytics and verification
google_analytics_id:
google_site_verification:
bing_site_verification:
baidu_site_verification:

# Site Author
author:
  name: "郭开喆"
  avatar: "images/profile.svg"
  bio: "东南大学青年首席教授、博士生导师"
  location: "南京，中国"
  employer: "东南大学 / 紫金山实验室"
  googlescholar:
  email: "kaizhe.guo@seu.edu.cn"
  dblp: "https://dblp.org/pid/212/6768.html"
  orcid: "https://orcid.org/0000-0001-6509-3541"
  researchgate:
  uri:
  github:
  linkedin:
  twitter:
  weibo:
  zhihu:

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - local
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Asia/Shanghai

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development
